---
title: "Pre-Conference Communications"
editor: source
---

## September 12, 2025

Hello everyone! We are excited to spend the day with you for the End-to-End Submissions in R with the Pharmaverse workshop at posit::conf on Tuesday, September 16!

In this workshop, we’ll give a high level overview of the scope and tools available within the Pharmaverse for the clinical pipeline, focusing on SDTM through outputs. Our hope is that you will walk away with an understanding of how to use R for every stage of the submission process.. A basic understanding of R and tidyverse is expected for this workshop. More information about the workshop can be found here: https://posit-conf-2025.github.io/pharmaverse/ (will be updated up to the workshop).

For the day to run smoothly, please be sure to bring your own laptop and charger so you can follow along and do the exercises. We will be using Posit Cloud, so you don’t need to worry about getting anything installed on your computer. Just make sure you have a free Posit Cloud account before the workshop starts.

During the workshop, we will be using Slack as our main communication method. Steps to join us there:

- First, join the Pharmaverse Slack here: [https://pharmaverse.slack.com/](https://pharmaverse.slack.com/)

- Find our dedicated Slack channel: [https://pharmaverse.slack.com/archives/C09AFHP4JUT](https://pharmaverse.slack.com/archives/C09AFHP4JUT). If you have any questions before the workshop, please feel free to drop them in the Slack channel. See you in Atlanta!

Your instructors,

Becca, Ben, Daniel, and Ram


## September 15, 2025

Hi everyone,

In case you had trouble joining the Slack – Please be on the lookout for an invitation to your email to join the workshop Slack channel directly.  

Thanks!

Becca
